# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 04:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from datetime import datetime
import csv


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0001_initial'),
    ]

    operations = [
        
    ]
