# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0004_auto_20160507_0543'),
    ]

    operations = [
    ]
