# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=320)),
                ('genres', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('rater_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField()),
                ('time', models.DateTimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings_app.Movie')),
                ('rater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings_app.Rater')),
            ],
        ),
    ]
