# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 18:30
from __future__ import unicode_literals
import csv
from django.db import migrations
from datetime import datetime
# from ratings_app.models import Movie, Rating



def func(apps, schema_editor):
        Movie = apps.get_model("ratings_app", "Movie")
        Rating = apps.get_model("ratings_app", "Rating")
        Rater = apps.get_model("ratings_app", "Rater")

        with open('../ml-latest-small/movies.csv','r') as data_file:
            reader = csv.DictReader(data_file)
            for each_movie in reader:
                new_movie = Movie(movie_id=each_movie['movieId'], title=each_movie['title'], genres=each_movie['genres'])
                new_movie.save()

        with open('../ml-latest-small/ratings.csv','r') as data_file:
            reader = csv.DictReader(data_file)
            for each_rating in reader:
                new_rater = Rater(rater_id=each_rating['userId'])
                new_rater.save()
                mid = Movie.objects.get(movie_id=each_rating['movieId'])
                rid = new_rater#each_rating['userId']
                rv = each_rating['rating']
                ts = datetime.fromtimestamp(float(each_rating['timestamp']))
                new_rating = Rating(movie_id=mid, rater_id=rid, rating_value=rv,time=ts)
                new_rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(func)
    ]
