# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0003_auto_20160505_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='rater_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater_id',
            new_name='rater',
        ),
    ]
