# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:36
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.models import User
import random


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0004_auto_20160505_2102'),
    ]

    operations = [
    ]
