# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 20:21
from __future__ import unicode_literals

from django.db import migrations
import random
from django.contrib.auth.models import User

# User.object.create_user()
def randomword(length):
   return ''.join(random.choice(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u',
                                 'v','w','x','y','z']) for i in range(length))

def add_users(apps, schema_editor):
    Movie = apps.get_model("ratings_app", "Movie")
    Rating = apps.get_model("ratings_app", "Rating")
    Rater = apps.get_model("ratings_app", "Rater")
    for each_rater in Rater.objects.all():
        user_name  = randomword(10)
        new_user = User.objects.create_user(username=user_name,password='moviepassword')
        new_user.save()

def rem_user(apps, schema_editor):
    User.objects.get(is_superuser=False).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0005_auto_20160506_1936'),
    ]

    operations = [
        migrations.RunPython(add_users, reverse_code = rem_user)
    ]
