# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0002_auto_20160509_1805'),
    ]

    operations = [
    ]
