# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0003_auto_20160509_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
