# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0005_auto_20160509_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
