# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0007_auto_20160507_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='user',
        ),
    ]
